In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
Data = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
Data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
Data['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [5]:
Data.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [6]:
data = Data.drop('stab',axis = 1)

In [7]:
X = data.drop(['stabf'],axis = 1)
Y = data['stabf']

In [16]:
Y

array([1, 0, 1, ..., 0, 1, 1])

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler

In [25]:
y_train

array([1, 1, 1, ..., 1, 1, 0])

In [26]:
stan = StandardScaler()
x_train_transformed = stan.fit_transform(x_train)
x_test_transformed = stan.transform(x_test)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rand = RandomForestClassifier(random_state = 1)

In [41]:
rand.fit(x_train_transformed,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [42]:
preds = rand.predict(x_test_transformed)

In [43]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,classification_report,confusion_matrix

In [44]:
acc1 = accuracy_score(y_test,preds)
print(acc1)

0.929


In [45]:
f1_1 = f1_score(y_test,preds)
print(f1_1)

0.9455521472392638


In [46]:
prec1 = precision_score(y_test,preds)
print(prec1)

0.9340909090909091


In [47]:
class1 = classification_report(y_test,preds)
print(class1)

              precision    recall  f1-score   support

           0       0.92      0.88      0.90       712
           1       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [48]:
conf1 = confusion_matrix(y_test,preds)
print(conf1)

[[ 625   87]
 [  55 1233]]


In [49]:
from sklearn.ensemble import ExtraTreesClassifier

In [50]:
extra = ExtraTreesClassifier(random_state = 1)
extra.fit(x_train_transformed,y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=1, verbose=0,
                     warm_start=False)

In [56]:
pred = extra.predict(x_test_transformed)

In [57]:
acc2 = accuracy_score(y_test,pred)
print(acc2)

0.928


In [58]:
f1_2 = f1_score(y_test,pred)
print(f1_2)

0.9455370650529501


In [59]:
prec2 = precision_score(y_test,pred)
print(prec2)

0.9218289085545722


In [60]:
class2 = classification_report(y_test,pred)
print(class2)

              precision    recall  f1-score   support

           0       0.94      0.85      0.89       712
           1       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [61]:
conf2 = confusion_matrix(y_test,pred)
print(conf2)

[[ 606  106]
 [  38 1250]]


In [89]:
imp = extra.feature_importances_
print(imp)

[0.11739736 0.11844468 0.11316851 0.11546569 0.03950675 0.04037132
 0.04070628 0.04057864 0.08978291 0.09367636 0.09688268 0.09401882]


In [62]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}
clf1 = RandomizedSearchCV(ExtraTreesClassifier(random_state=1), hyperparameter_grid, random_state=1)
search = clf1.fit(x_train_transformed, y_train)
search_pred = clf1.predict(x_test_transformed)
search.best_params_.values()

dict_values([1000, 2, 8, None])

In [67]:
acc3 = accuracy_score(y_test,search_pred)
print(acc3)
f1_3 = f1_score(y_test,search_pred)
print(f1_3)
prec3 = precision_score(y_test,search_pred)
print(prec3)

0.927
0.9441896024464832
0.9299698795180723


In [74]:
import xgboost as xgb

In [76]:
extreme = xgb.XGBClassifier(random_state = 1)

In [77]:
extreme.fit(x_train_transformed, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [78]:
ext_pred = extreme.predict(x_test_transformed)

In [79]:
acc4 = accuracy_score(y_test,ext_pred)
print(acc4)
f1_4 = f1_score(y_test,ext_pred)
print(f1_4)
prec4 = precision_score(y_test,ext_pred)
print(prec4)

0.9195
0.9388530193695404
0.9189591078066914


In [80]:
import lightgbm as lgb

In [85]:
light = lgb.LGBMClassifier(random_state = 1)

In [86]:
light.fit(x_train_transformed, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=1, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [87]:
light_pred = light.predict(x_test_transformed)

In [88]:
acc5 = accuracy_score(y_test,light_pred)
print(acc5)
f1_5 = f1_score(y_test,light_pred)
print(f1_5)
prec5 = precision_score(y_test,light_pred)
print(prec5)

0.9375
0.9520153550863725
0.9415337889141989


# QUESTION 1

In [112]:
True_Pos = 355
True_neg = 120
False_Pos = 1480
False_neg = 45
Precision = (True_Pos/(True_Pos+False_Pos))
Recall = (True_Pos/(True_Pos+False_neg))
F1 = 2 * (Precision * Recall) / (Precision + Recall)
print('f1_score is: ', F1)

f1_score is:  0.3176733780760626


# QUESTION 4

In [93]:
#Recall = TP/TP + FN
82/(82+18)*100
#FP is less than 10% and also multiplied by 5 equals 10 which also fulfills the criteria of it being less expensive than the false negative
#So the answer is A.TN = 98, FP = 2,FN = 12,TP = 18

82.0

# QUESTION 14

In [94]:
rand.fit(x_train_transformed,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [95]:
preds = rand.predict(x_test_transformed)

In [96]:
acc1 = accuracy_score(y_test,preds)
print(acc1)

0.929


# QUESTION 15

In [97]:
extreme.fit(x_train_transformed, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [98]:
ext_pred = extreme.predict(x_test_transformed)

In [99]:
acc4 = accuracy_score(y_test,ext_pred)
print(acc4)

0.9195


# QUESTION 16

In [100]:
light.fit(x_train_transformed, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=1, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [101]:
light_pred = light.predict(x_test_transformed)

In [102]:
acc5 = accuracy_score(y_test,light_pred)
print(acc5)

0.9375


# QUESTION 17

In [103]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}
clf1 = RandomizedSearchCV(ExtraTreesClassifier(random_state=1), hyperparameter_grid, random_state=1)
search = clf1.fit(x_train_transformed, y_train)
search_pred = clf1.predict(x_test_transformed)
search.best_params_.values()

dict_values([1000, 2, 8, None])

# QUESTION 18

In [105]:
#The two accuracy scores are the ones for the model for the ExtraTress Classifier and the RandomSearchCV after hyperperameter tuning respectively
print(acc2)
print(acc3)

0.928
0.927


#It is evident that after tuning the hyperparameters the accuracy reduced therefore the accuracy of the Extratreesclassifier does well without being tuned

# QUESTION 20

In [106]:
imp = extra.feature_importances_
print(imp)

[0.11739736 0.11844468 0.11316851 0.11546569 0.03950675 0.04037132
 0.04070628 0.04057864 0.08978291 0.09367636 0.09688268 0.09401882]


In [111]:
print(imp.min())
print(imp.max())

0.039506754233827476
0.11844468079199041


In [108]:
data.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

The imortance of features in percentage each corresponds with the names of columns, therefore the one with least is p1 while the column with most importance is tau2